package com.signalway.base;

public enum MqQueue {

	CAPTURE_TOLL_ALL_DATA_QUEUE("CAPTURE_TOLL_ALL_DATA_QUEUE","测试通道",MessageSendRoutingKey.EXPRESSWAY_CAPTURE_TOLL_ALL_DATA),
	DEVICE_UPDATEXCEPTION_QUEUE("DEVICE_UPDATEXCEPTION_QUEUE","更新设备异常通道",MessageSendRoutingKey.DEVICE_UPDATEEXCEPTION),
	DEVICE_NEWEXCEPTION_QUEUE("DEVICE_NEWEXCEPTION_QUEUE","新增设备异常通道",MessageSendRoutingKey.DEVICE_NEWEXCEPTION),
	DEVICE_NEWSTATUS_QUEUE("DEVICE_NEWSTATUS_QUEUE","新增设备状态通道",MessageSendRoutingKey.DEVICE_NEWSTATUS),
	DEVICE_CLOSEEXCEPTION_QUEUE("DEVICE_CLOSEEXCEPTION_QUEUE","关闭设备异常通道",MessageSendRoutingKey.DEVICE_CLOSEEXCEPTION),
	DEVICE_UPDATEDEVCIEINFO_QUEUE("DEVICE_UPDATEDEVCIEINFO_QUEUE","更新设备信息通道",MessageSendRoutingKey.DEVICE_UPDATEDEVCIEINFO),
	DEVICE_UPLOADBAYONE_QUEUE("DEVICE_UPLOADBAYONE_QUEUE","上传卡口数据通道",MessageSendRoutingKey.DEVICE_UPLOADBYONET),
	DEVICE_UPLOADSTATUS_QUEUE("DEVICE_UPLOADSTATUS_QUEUE","上传一般状态数据通道",MessageSendRoutingKey.DEVICE_UPLOADSTATUS),
	DEVICE_UPDATESTATUS_QUEUE("DEVICE_UPDATESTATUS_QUEUE","设备更新一般状态数据通道",MessageSendRoutingKey.DEVICE_UPDATESTATUS),
	DEVICE_UPLOADINSPECTIONPIC_QUEUE("DEVICE_UPLOADINSPECTIONPIC_QUEUE","上传巡检图片通道",MessageSendRoutingKey.DEVICE_UPLOADINSPECTIONPIC),
	DEVICE_UPLOADWARNING_QUEUE("DEVICE_UPLOADWARNING_QUEUE","上传预警信息通道",MessageSendRoutingKey.DEVICE_UPLOADWARNING),
	DEVICE_UPLOADEXCEPTION_QUEUE("DEVICE_UPLOADEXCEPTION_QUEUE","上传异常信息通道",MessageSendRoutingKey.DEVICE_UPLOADEXCEPTION),
	DEVICE_UPLOADRESET_QUEUE("DEVICE_UPLOADRESET_QUEUE","上传复位信息通道",MessageSendRoutingKey.DEVICE_UPLOADRESET),
	MAN_REPORT_EXCEPTION_QUEUE("MAN_REPORT_EXCEPTION_QUEUE","人工上报故障通道",MessageSendRoutingKey.MAN_REPORT_EXCEPTION),
	SYSTEM_REPORT_EXCEPTION_QUEUE("SYSTEM_REPORT_EXCEPTION_QUEUE","系统上报故障通道",MessageSendRoutingKey.SYSTEM_REPORT_EXCEPTION),
	ALLOT_EXCEPTION_QUEUE("ALLOT_EXCEPTION_QUEUE","分配故障通道",MessageSendRoutingKey.ALLOT_EXCEPTION),
	CONFRIM_EXCEPTION_QUEUE("CONFRIM_EXCEPTION_QUEUE","审核故障通道",MessageSendRoutingKey.CONFRIM_EXCEPTION),
	STATISTICS_UPLOADDAYWARNING_QUEUE("STATISTICS_UPLOADDAYWARNING_QUEUE","上传当天预警次数数据通道",MessageSendRoutingKey.STATISTICS_UPLOADDAYWARNING),
	STATISTICS_UPLOADHOURFLOW_QUEUE("STATISTICS_UPLOADHOURFLOW_QUEUE","上传小时车流量数据通道",MessageSendRoutingKey.STATISTICS_UPLOADHOURFLOW),
	STATISTICS_UPLOADDAYFLOW_QUEUE("STATISTICS_UPLOADDAYFLOW_QUEUE","上传当天车流量数据通道",MessageSendRoutingKey.STATISTICS_UPLOADDAYFLOW),
	ENDINSPECTION_QUEUE("ENDINSPECTION_QUEUE","结束巡检通道",MessageSendRoutingKey.INSPECTION_END),
	;
	
	private String queueName;
	private String queuedescribe;
	private MessageSendRoutingKey routkey;
	
	
	MqQueue(String queueName, String queuedescribe, MessageSendRoutingKey routkey){
		this.queuedescribe=queuedescribe;
		this.queueName = queueName;
		this.routkey = routkey;
	}


	public String getQueueName() {
		return queueName;
	}


	

	public String getQueuedescribe() {
		return queuedescribe;
	}


	public MessageSendRoutingKey getRoutkey() {
		return routkey;
	}


	
	
}
