package com.mybatis.dao.master.aa;

import com.mybatis.dao.master.aa.TestDatetime;
import java.util.List;

public interface TestDatetimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_datetime
     *
     * @mbg.generated Tue Apr 16 11:57:09 CST 2019
     */
    int insert(TestDatetime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test_datetime
     *
     * @mbg.generated Tue Apr 16 11:57:09 CST 2019
     */
    List<TestDatetime> selectAll();
}