package com.utils.xlsx;

public enum XlsModuleFile {
	CARANTICIPATION_OUT,
	SERVICE_AREA_RETENTION_OUT,
	ETC_DATA_OUT,
	CAR_PATH_OUT,
	CAR_BALCK_OUT,
	EXDATA_OUT,
	CAR_HISTORY_DATA_OUT,
	CARINOUT_DATA_OUT;

}
